"""empty message

Revision ID: 08e956fed1bb
Revises: 10dc22328b37
Create Date: 2025-11-27 05:08:55.485127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e956fed1bb'
down_revision = '10dc22328b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_people', sa.Integer(), nullable=False),
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_people'], ['people.id'], ),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_user', 'id_people', 'id_planet')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_people', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_planet', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_people'], ['people.id'], name='favorite_id_people_fkey'),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], name='favorite_id_planet_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='favorite_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', 'id_user', 'id_people', 'id_planet', name='favorite_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
